#spring:
#  application:
#    name: User
#  datasource:
#    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
#    username: root
#    password: 0000
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#server:
#  port: 8081